### ISSUE TITLE
Can not run tests

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/wdio-allure-reporter#18]
@gronke @just-boris I can't run the tests, getting:

```
Running "mochaTest:test" (mochaTest) task
>> Mocha exploded!
>> SyntaxError: Unexpected token ...
>>     at exports.runInThisContext (vm.js:53:16)
>>     at Module._compile (module.js:387:25)
>>     at Object.Module._extensions..js (module.js:422:10)
>>     at Module.load (module.js:357:32)
>>     at Function.Module._load (module.js:314:12)
>>     at Module.require (module.js:367:17)
>>     at require (internal/module.js:16:19)
>>     at Object.<anonymous> (/Users/christianbromann/Sites/Webprojekte/webdriverjs/wdio-allure-reporter/test/specs/after.js:4:14)
>>     at Module._compile (module.js:413:34)
>>     at Object.Module._extensions..js (module.js:422:10)
Warning: Task "mochaTest:test" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by gronke** [comment]
@christian-bromann executing the tests with this command should work.
```
node --harmony_rest_parameters ./node_modules/grunt-cli/bin/grunt test
```

**Comment by gronke** [comment]
.. anyway. The tests are still all failing :-) But this time for a different reason. Will investigate and push a fix.

**Comment by christian-bromann** [comment]
@gronke thanks

**Comment by christian-bromann** [comment]
I can confirm they are still failing for me too

**Comment by christian-bromann** [comment]
Can't we just use babel as mocha compiler and use all the nice ES2016 stuff for tests too?

**Comment by just-boris** [comment]
Sorry, I have Node 6 on my local machine and it supports most of modern features. Yes, I also vote for enable Babel for tests. Then we can use `import` statement as well as it used in `lib` directory
