### ISSUE TITLE
unable to get screenshots and wdio session is not terminated properly BaseReporter.js:336

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/wdio-allure-reporter#44]
_From @straweb on June 16, 2017 20:40_

## unable to get screenshots and wdio session is not terminated properly
```
project\node_modules\webdriverio\build\lib\utils\BaseReporter.js:336
                        throw _iteratorError;
                        ^
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at new Buffer (buffer.js:80:17)
    at AllureReporter.<anonymous> (project\node_modules\wdio-allure-reporter\build\reporter.js:134:52)
    at emitOne (events.js:96:13)
    at AllureReporter.emit (events.js:188:7)
    at BaseReporter.handleEvent (project\node_modules\webdriverio\build\lib\utils\BaseReporter.js:324:35)
    at Launcher.messageHandler (project\node_modules\webdriverio\build\lib\launcher.js:623:28)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
[01:29:37]      Failed to take screenshot on reject:     {"message":"no such window: target window already closed\nfrom unknown error: web view not found","type":"RuntimeError","seleniumStack":{"status":23,"type":"NoSuchWindow","message":"A request to switch to a different window could not be satisfied because the window could not be found.","orgStatusMessage":"no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=58.0.3029.110)\n  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc56791 ... (1134 more bytes)"}}
```

## Environment

* WebdriverIO version: 4.4.0
* Node.js version: v6.9.4 npm 3.10.10
* wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details
Earlier I can see error screenshots but in parent folder instead of taking .errorShots/ folder location which is given in config. for some errors its not taking errorshots at all and terminating.  

_Copied from original issue: webdriverio/webdriverio#2149_

**Comment by just-boris** [comment]
The problem in the following line: https://github.com/webdriverio/wdio-allure-reporter/blob/master/lib/reporter.js#L99

Somehow it happened, that screenshot comand did not give us any screenshot. In order to fix that, we can just add a simple condition around it, but before I would like to understand, why that has happened.

@straweb, are you getting this on a regular basis? Could you provide an example, that reproduces it?

**Comment by straweb** [comment]
yes

```
17:32:36.665 WARN - Exception: timeout
  (Session info: chrome=58.0.3029.110)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 300.08 seconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'hostid', ip: 'xx.xx.xxx.xxx', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29.461591(62ebf098771772160f391d75e589dc567915b233), userDataDir=C:\Users\TSEELA~1\AppData\Local\Temp\scoped_dir10772_20965}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=58.0.3029.110, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 7ce4f1e549401f8c6db83e1d1f4e69d6

17:33:36.033 INFO - Executing: [take screenshot])

D:\project\node_modules\webdriverio\build\lib\utils\BaseReporter.js:336
                        throw _iteratorError;
                        ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at new Buffer (buffer.js:80:17)
    at AllureReporter.<anonymous> (D:\project\node_modules\wdio-allure-reporter\build\reporter.js:134:52)
    at emitOne (events.js:96:13)
    at AllureReporter.emit (events.js:188:7)
    at BaseReporter.handleEvent (D:\project\node_modules\webdriverio\build\lib\utils\BaseReporter.js:324:35)
    at Launcher.messageHandler (D:\project\node_modules\webdriverio\build\lib\launcher.js:623:28)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
'true' is not recognized as an internal or external command,
operable program or batch file.

```

**Comment by just-boris** [comment]
Well, can you also show us the code of the test, that failed?

**Comment by skuppusw** [comment]
I also get this error regularly now. @just-boris @straweb 

I use WebdriverIO - 4.8.0
Npm - Wdio-allure-reporter - 0.1.2

D:\BuildAgent\work\f0e11dea6f42e7a2\node_modules\webdriverio\build\lib\utils\BaseReporter.js:336
[23:04:56][Step 2/3]                         throw _iteratorError;
[23:04:56][Step 2/3]                         ^
[23:04:56][Step 2/3] 
[23:04:56][Step 2/3] TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
[23:04:56][Step 2/3]     at fromObject (buffer.js:262:9)
[23:04:56][Step 2/3]     at Function.Buffer.from (buffer.js:101:10)
[23:04:56][Step 2/3]     at new Buffer (buffer.js:80:17)
[23:04:56][Step 2/3]     at AllureReporter.<anonymous> (D:\BuildAgent\work\f0e11dea6f42e7a2\node_modules\wdio-allure-reporter\build\reporter.js:134:52)
[23:04:56][Step 2/3]     at emitOne (events.js:96:13)
[23:04:56][Step 2/3]     at AllureReporter.emit (events.js:188:7)
[23:04:56][Step 2/3]     at BaseReporter.handleEvent (D:\BuildAgent\work\f0e11dea6f42e7a2\node_modules\webdriverio\build\lib\utils\BaseReporter.js:324:35)
[23:04:56][Step 2/3]     at Launcher.messageHandler (D:\BuildAgent\work\f0e11dea6f42e7a2\node_modules\webdriverio\build\lib\launcher.js:623:28)
[23:04:56][Step 2/3]     at emitTwo (events.js:106:13)
[23:04:56][Step 2/3]     at ChildProcess.emit (events.js:191:7)
[23:04:56][Step 2/3] Process exited with code 1

**Comment by just-boris** [comment]
In my previous comment, I have requested a code sample, that will help me to figure out the reason.

@skuppusw if you constantly have this error, please share a code example.

**Comment by ajw015** [comment]
FYI, I am also hitting this issue with a project using the same versions as skuppusw above, and also generating the report with allure-commandline 2.3.3 ... I have seen it run successfully so it seems to be some sort of race condition. Sorry I can't provide more information just-boris but I think the null check easy suggestion you had would suffice for us.

**Comment by ViaMay** [comment]
I had this error too but I delete the line  
> screenshotPath:  'screenshots'

in my file wdio.conf.js and then everything became good

**Comment by jgsheffer** [comment]
I always receive this error when there is a alert dialog on the screen.  Wdio doesn't seem to be able to take a screenshot when there are some types of blocking alerts visible.

**Comment by psmod2** [comment]
Any update on this - an allure report without screenshots isn't very useful.

Any workaround I can temporarily use?

**Comment by christian-bromann** [comment]
@psmod2 I am not actively working on this so help would be much appreciated

**Comment by ajw015** [comment]
Maybe just adding a null-check to the screenshot creation line 99? 
https://github.com/webdriverio/wdio-allure-reporter/blob/master/lib/reporter.js#L99
